package java24h;

import java.util.Arrays;
import java.util.Random;

public class BakverkBas extends javax.swing.JFrame {
//Skapar upp array och hjälpvariabler

    Bakverk[] bakelseArray = new Bakverk[30];
    int index = 0;
    int bladdra = 0;

    public BakverkBas() {

        //Nya objekt ur Bakverkklassen.
        Bakverk bakelse1 = new Bakverk("Kanelbulle", "Pågen", 20, 32, "Ja", "Stor", 60);
        Bakverk bakelse2 = new Bakverk("Semla", "Perers Bröd", 27, 12, "Ja", "Mellan", 80);
        Bakverk bakelse3 = new Bakverk("Rulltårta", "Rättviksbagarn", 15, 5, "Nej", "Liten", 30);

        //Placera objekt i array
        bakelseArray[0] = bakelse1;
        bakelseArray[1] = bakelse2;
        bakelseArray[2] = bakelse3;
        bakelseArray[0].getProduktId();
        bakelseArray[1].getProduktId();
        bakelseArray[2].getProduktId();

        initComponents();
    }

    //Hjälpmedtod, printar ut arrayen
    private void fyllTextArea() {

        taRegister.setText(null);

        for (Bakverk temp : bakelseArray) {

            if (temp != null) {

                taRegister.append(temp.getBakverk());
            }
        }
    }

    private void antalKanelBulle() {
        int antal = 0;

        for (Bakverk temp : bakelseArray) {
            if (temp != null) {
                if (temp.getProduktTyp().equalsIgnoreCase("kanelbulle")) {
                    antal++;
                }
            }
        }
        lblKanelbulle.setText("Antal med produkttyp Kanelbulle: " + antal);
    }

    private void antalSemla() {
        int antal = 0;

        for (Bakverk temp : bakelseArray) {
            if (temp != null) {
                if (temp.getProduktTyp().equalsIgnoreCase("semla")) {
                    antal++;
                }
            }
        }
        lblSemla.setText("Antal med produkttyp Semla: " + antal);
    }

    private void antalBakelser() {
        int antal = 0;
        for (Bakverk temp : bakelseArray) {
            if (temp != null) {
                antal += temp.getAntal();
            }
        }
        lblAntalBakelser.setText("Antal bakverk i lager: " + antal + "st");
    }

    private void totalPris() {

        int pris = 0;
        for (Bakverk temp : bakelseArray) {
            if (temp != null) {

                for (int i = 0; i < temp.getAntal(); i++) {
                    pris += temp.getPris();
                }

            }
        }
        lblTotalPris.setText("Totalt pris för alla bakelser: " + pris + "kr");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblProduktId = new javax.swing.JLabel();
        tfProduktId = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRegister = new javax.swing.JTextArea();
        tfProduktTyp = new javax.swing.JTextField();
        tfMarke = new javax.swing.JTextField();
        tfPris = new javax.swing.JTextField();
        tfAntal = new javax.swing.JTextField();
        tfBakeOff = new javax.swing.JTextField();
        tfStorlek = new javax.swing.JTextField();
        tfVikt = new javax.swing.JTextField();
        lblProduktTyp = new javax.swing.JLabel();
        lblMarke = new javax.swing.JLabel();
        lblPris = new javax.swing.JLabel();
        lblAntal = new javax.swing.JLabel();
        lblBakeOff = new javax.swing.JLabel();
        lblStorlek = new javax.swing.JLabel();
        lblVikt = new javax.swing.JLabel();
        btnVisa = new javax.swing.JButton();
        btnSpara = new javax.swing.JButton();
        btnSidVy = new javax.swing.JButton();
        btnBacka = new javax.swing.JButton();
        btnNasta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lbltaBortProduktId = new javax.swing.JLabel();
        tfTaBortId = new javax.swing.JTextField();
        btnTaBortId = new javax.swing.JButton();
        lblSokProduktTyp = new javax.swing.JLabel();
        tfSokProduktTyp = new javax.swing.JTextField();
        lblSokMarke = new javax.swing.JLabel();
        tfSokMarke = new javax.swing.JTextField();
        btnSokProduktMarke = new javax.swing.JButton();
        lblSokVarorPris = new javax.swing.JLabel();
        tfSokPaPris = new javax.swing.JTextField();
        btnSokPaPris = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfUppdateraPris = new javax.swing.JTextField();
        tfUppdateraAntal = new javax.swing.JTextField();
        btnUppdateraPris = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        tfIdUppdatera = new javax.swing.JTextField();
        btnUppdateraAntal = new javax.swing.JButton();
        lblSemla = new javax.swing.JLabel();
        lblKanelbulle = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAntalBakelser = new javax.swing.JLabel();
        lblTotalPris = new javax.swing.JLabel();
        btnSortera = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblProduktId.setText("Produkt ID:");

        tfProduktId.setEditable(false);
        tfProduktId.setBackground(new java.awt.Color(153, 153, 153));

        taRegister.setColumns(20);
        taRegister.setRows(5);
        jScrollPane1.setViewportView(taRegister);

        lblProduktTyp.setText("Produkttyp:");

        lblMarke.setText("Märke:");

        lblPris.setText("Pris(kr):");

        lblAntal.setText("Antal:");

        lblBakeOff.setText("Bake off:");

        lblStorlek.setText("Storlek:");

        lblVikt.setText("Vikt (g):");

        btnVisa.setText("Visa");
        btnVisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaActionPerformed(evt);
            }
        });

        btnSpara.setText("Spara");
        btnSpara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSparaActionPerformed(evt);
            }
        });

        btnSidVy.setText("Sidvy");
        btnSidVy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSidVyActionPerformed(evt);
            }
        });

        btnBacka.setText("<");
        btnBacka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackaActionPerformed(evt);
            }
        });

        btnNasta.setText(">");
        btnNasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNastaActionPerformed(evt);
            }
        });

        lbltaBortProduktId.setText("Ta bort produkt på ID");

        btnTaBortId.setText("Ta bort (Id)");
        btnTaBortId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortIdActionPerformed(evt);
            }
        });

        lblSokProduktTyp.setText("Sök på produkttyp");

        lblSokMarke.setText("Sök på märke");

        btnSokProduktMarke.setText("Sök på märke & produkt");
        btnSokProduktMarke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokProduktMarkeActionPerformed(evt);
            }
        });

        lblSokVarorPris.setText("Sök på varor under pris:");

        btnSokPaPris.setText("Sök på pris");
        btnSokPaPris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokPaPrisActionPerformed(evt);
            }
        });

        jLabel2.setText("Uppdatera pris: ");

        jLabel3.setText("Uppdatera antal:");

        tfUppdateraAntal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUppdateraAntalActionPerformed(evt);
            }
        });

        btnUppdateraPris.setText("Uppdatera");
        btnUppdateraPris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateraPrisActionPerformed(evt);
            }
        });

        jLabel4.setText("Produkt ID att uppdatera:");

        btnUppdateraAntal.setText("Uppdatera");
        btnUppdateraAntal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdateraAntalActionPerformed(evt);
            }
        });

        btnSortera.setText("Sortera");
        btnSortera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSorteraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(btnBacka)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProduktId)
                                    .addComponent(lblProduktTyp)
                                    .addComponent(lblMarke)
                                    .addComponent(lblPris)
                                    .addComponent(lblAntal))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfProduktId, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                        .addComponent(tfProduktTyp))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(tfPris, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                                        .addComponent(tfAntal, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfMarke, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                        .addGap(145, 145, 145))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnSortera)
                                .addGap(111, 111, 111)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btnSidVy)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblStorlek)
                                            .addComponent(lblVikt)
                                            .addComponent(lblBakeOff)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(btnSpara)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(tfStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(btnTaBortId, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(tfBakeOff, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(30, 30, 30)
                                                .addComponent(lbltaBortProduktId)
                                                .addGap(35, 35, 35)
                                                .addComponent(tfTaBortId, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(63, 63, 63)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel1)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(lblSokVarorPris))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jLabel2)
                                                        .addGap(18, 18, 18)
                                                        .addComponent(tfUppdateraPris, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnUppdateraPris)
                                                    .addComponent(tfSokPaPris, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSokPaPris)
                                                .addGap(14, 14, 14))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(tfVikt, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(btnVisa))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(btnSokProduktMarke)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblSokProduktTyp)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfSokProduktTyp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblSokMarke, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(tfSokMarke, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel3)))
                                        .addGap(18, 18, 18)
                                        .addComponent(tfUppdateraAntal, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUppdateraAntal)))
                                .addGap(86, 86, 86))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(261, 261, 261)
                                .addComponent(lblKanelbulle, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(110, 110, 110))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(367, 367, 367)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tfIdUppdatera, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 559, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSemla, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnNasta))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAntalBakelser, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTotalPris, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProduktId)
                    .addComponent(tfProduktId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfBakeOff, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBakeOff)
                    .addComponent(jLabel1)
                    .addComponent(lbltaBortProduktId)
                    .addComponent(tfTaBortId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSokVarorPris, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSokPaPris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfProduktTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProduktTyp)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfStorlek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStorlek)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTaBortId)
                            .addComponent(btnSokPaPris))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMarke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMarke)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfVikt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblVikt)
                            .addComponent(lblSokProduktTyp)
                            .addComponent(tfSokProduktTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfUppdateraPris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUppdateraPris))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfPris, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPris))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(tfAntal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAntal)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnSpara)
                                    .addComponent(btnVisa))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSidVy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSortera)
                                .addGap(12, 12, 12))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfUppdateraAntal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUppdateraAntal)
                            .addComponent(jLabel3))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblSokMarke)
                                    .addComponent(tfSokMarke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfIdUppdatera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(btnSokProduktMarke)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lblAntalBakelser, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblTotalPris, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(158, 158, 158))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnBacka)
                            .addGap(354, 354, 354)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblSemla, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblKanelbulle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel5)))
                        .addGap(51, 51, 51)
                        .addComponent(btnNasta)
                        .addGap(92, 92, 92))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaActionPerformed
        // TODO add your handling code here:
        antalKanelBulle();
        antalSemla();
        antalBakelser();
        totalPris();
        fyllTextArea();
    }//GEN-LAST:event_btnVisaActionPerformed

    private void btnSparaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSparaActionPerformed
        String produktTyp = tfProduktTyp.getText();
        String marke = tfMarke.getText();
        int pris = Integer.parseInt(tfPris.getText());
        int antal = Integer.parseInt(tfAntal.getText());
        String bakeOff = tfBakeOff.getText();
        String storlek = tfStorlek.getText();
        int vikt = Integer.parseInt(tfVikt.getText());
        int funnenProduktId = 0;

        Bakverk bakelse = new Bakverk(produktTyp, marke, pris, antal, bakeOff, storlek, vikt);
        String produktId = bakelse.getProduktId();

        for (Bakverk temp : bakelseArray) {
            if (temp != null && produktId.equalsIgnoreCase(temp.getProduktId())) {
                funnenProduktId++;

            }
        }

        for (int i = 0; i < bakelseArray.length; i++) {
            if (bakelseArray[i] == null && funnenProduktId == 0) {
                bakelseArray[i] = bakelse;
                break;
            }
        }

        tfProduktId.setText(produktId);
        if (funnenProduktId > 0) {
            taRegister.setText("ProduktId: " + produktId + " finns redan registrerad, var vänlig registrera annan produkt.");
        } else {
            fyllTextArea();
        }

    }//GEN-LAST:event_btnSparaActionPerformed

    private void btnBackaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackaActionPerformed
        if (bladdra > 0) {
            bladdra--;

    }//GEN-LAST:event_btnBackaActionPerformed
        taRegister.setText(bakelseArray[bladdra].getBakverk());
    }
    private void btnSidVyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSidVyActionPerformed
        for (Bakverk bladdra : bakelseArray) {
            taRegister.setText(bladdra.getBakverk());
            break;
        }
    }//GEN-LAST:event_btnSidVyActionPerformed

    private void btnNastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNastaActionPerformed

        if (bladdra < bakelseArray.length) {
            bladdra++;

        }
        if (bakelseArray[bladdra] != null) {
            taRegister.setText(bakelseArray[bladdra].getBakverk());
        } else {
            bladdra--;

    }//GEN-LAST:event_btnNastaActionPerformed
    }
    private void btnTaBortIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortIdActionPerformed
        String taBortProduktId = tfTaBortId.getText();

        for (int i = 0; i < bakelseArray.length; i++) {
            if (bakelseArray[i] != null && bakelseArray[i].getProduktId().equalsIgnoreCase(taBortProduktId)) {
                bakelseArray[i] = null;
                break;
            }
        }
        fyllTextArea();
    }//GEN-LAST:event_btnTaBortIdActionPerformed

    private void btnSokProduktMarkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokProduktMarkeActionPerformed
        String finnMarke = tfSokMarke.getText();
        String finnProduktTyp = tfSokProduktTyp.getText();
        taRegister.setText(null);

        for (Bakverk temp : bakelseArray) {
            if (temp != null) {
                if (temp.getProduktTyp().equalsIgnoreCase(finnProduktTyp) || temp.getMarke().equalsIgnoreCase(finnMarke)) {
                    taRegister.append(temp.getBakverk());
                }
            }
        }
    }//GEN-LAST:event_btnSokProduktMarkeActionPerformed

    private void btnSokPaPrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokPaPrisActionPerformed

        int sokPaPris = Integer.parseInt(tfSokPaPris.getText());

        taRegister.setText(null);
        for (Bakverk temp : bakelseArray) {
            if (temp != null) {
                if (temp.getPris() < sokPaPris) {
                    taRegister.append(temp.getBakverk());
                }
            }
        }

    }//GEN-LAST:event_btnSokPaPrisActionPerformed

    private void tfUppdateraAntalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUppdateraAntalActionPerformed

    }//GEN-LAST:event_tfUppdateraAntalActionPerformed

    private void btnUppdateraPrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateraPrisActionPerformed

        String finnProduktId = tfIdUppdatera.getText();

        for (Bakverk temp : bakelseArray) {
            if (temp != null) {

                if (temp.getProduktId().equalsIgnoreCase(finnProduktId)) {
                    if (tfUppdateraPris.getText() != null) {
                        temp.setPris(Integer.parseInt(tfUppdateraPris.getText()));
                    }

                    taRegister.setText(temp.getBakverk());
                }

            }
        }
    }//GEN-LAST:event_btnUppdateraPrisActionPerformed

    private void btnUppdateraAntalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdateraAntalActionPerformed
        String finnProduktId = tfIdUppdatera.getText();

        for (Bakverk temp : bakelseArray) {
            if (temp != null) {

                if (temp.getProduktId().equalsIgnoreCase(finnProduktId)) {
                    if (tfUppdateraAntal.getText() != null) {
                        temp.setAntal(Integer.parseInt(tfUppdateraAntal.getText()));
                    }

                    taRegister.setText(temp.getBakverk());
                }

            }
        }
    }//GEN-LAST:event_btnUppdateraAntalActionPerformed

    private void btnSorteraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSorteraActionPerformed
        taRegister.setText(null);
        Arrays.sort(bakelseArray, new BakelseSortering());
        for (Bakverk temp : bakelseArray) {
            if (temp != null) {

                taRegister.append(temp.getBakverk());

            }
        }
    }//GEN-LAST:event_btnSorteraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BakverkBas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BakverkBas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BakverkBas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BakverkBas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BakverkBas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBacka;
    private javax.swing.JButton btnNasta;
    private javax.swing.JButton btnSidVy;
    private javax.swing.JButton btnSokPaPris;
    private javax.swing.JButton btnSokProduktMarke;
    private javax.swing.JButton btnSortera;
    private javax.swing.JButton btnSpara;
    private javax.swing.JButton btnTaBortId;
    private javax.swing.JButton btnUppdateraAntal;
    private javax.swing.JButton btnUppdateraPris;
    private javax.swing.JButton btnVisa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAntal;
    private javax.swing.JLabel lblAntalBakelser;
    private javax.swing.JLabel lblBakeOff;
    private javax.swing.JLabel lblKanelbulle;
    private javax.swing.JLabel lblMarke;
    private javax.swing.JLabel lblPris;
    private javax.swing.JLabel lblProduktId;
    private javax.swing.JLabel lblProduktTyp;
    private javax.swing.JLabel lblSemla;
    private javax.swing.JLabel lblSokMarke;
    private javax.swing.JLabel lblSokProduktTyp;
    private javax.swing.JLabel lblSokVarorPris;
    private javax.swing.JLabel lblStorlek;
    private javax.swing.JLabel lblTotalPris;
    private javax.swing.JLabel lblVikt;
    private javax.swing.JLabel lbltaBortProduktId;
    private javax.swing.JTextArea taRegister;
    private javax.swing.JTextField tfAntal;
    private javax.swing.JTextField tfBakeOff;
    private javax.swing.JTextField tfIdUppdatera;
    private javax.swing.JTextField tfMarke;
    private javax.swing.JTextField tfPris;
    private javax.swing.JTextField tfProduktId;
    private javax.swing.JTextField tfProduktTyp;
    private javax.swing.JTextField tfSokMarke;
    private javax.swing.JTextField tfSokPaPris;
    private javax.swing.JTextField tfSokProduktTyp;
    private javax.swing.JTextField tfStorlek;
    private javax.swing.JTextField tfTaBortId;
    private javax.swing.JTextField tfUppdateraAntal;
    private javax.swing.JTextField tfUppdateraPris;
    private javax.swing.JTextField tfVikt;
    // End of variables declaration//GEN-END:variables
}
